### ISSUE TITLE
2.0.3 is missing preview in exports

### ISSUE THREAD

**Issue by OskarPersson** [alexgorbatchev/storybook-addon-localstorage#5]
The error I'm getting:

> Missing "./dist/preview.js" specifier in "@alexgorbatchev/storybook-addon-localstorage" package

**Comment by alexgorbatchev** [comment]
Could you please describe your setup? We are using this package in a production environment with SB8 w/o any issues.

**Comment by OskarPersson** [comment]
Steps to reproduce:

1. Create and go to a new directory
2. Install Storybook: 
```
npx storybook@latest init
```
3. Install addon
```
npm i --save-dev @alexgorbatchev/storybook-addon-localstorage
```
4. Add `@alexgorbatchev/storybook-addon-localstorage` to list of addons in `.storybook/main.ts`
5. Run storybook with `npm run storybook`

```
oskar@Oskars-MacBook-Pro ~/g/t/sb (main)> npm run storybook

> sb@0.0.0 storybook
> storybook dev -p 6006

@storybook/core v8.3.0

(node:37482) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
info => Starting manager..
info => Starting preview..
info Using tsconfig paths for react-docgen
╭─────────────────────────────────────────────────────╮
│                                                     │
│   Storybook 8.3.0 for react-vite started            │
│   197 ms for manager and 827 ms for preview         │
│                                                     │
│    Local:            http://localhost:6006/         │
│    On your network:  http://192.168.18.229:6006/    │
│                                                     │
╰─────────────────────────────────────────────────────╯
11:33:18 AM [vite] Pre-transform error: Missing "./dist/preview.js" specifier in "@alexgorbatchev/storybook-addon-localstorage" package
11:33:18 AM [vite] Internal server error: Missing "./dist/preview.js" specifier in "@alexgorbatchev/storybook-addon-localstorage" package
  Plugin: vite:import-analysis
  File: /virtual:/@storybook/builder-vite/vite-app.js
      at e (file:///Users/oskar/git/testproject/sb/node_modules/vite/dist/node/chunks/dep-CUvs3bbV.js:45978:25)
      at n (file:///Users/oskar/git/testproject/sb/node_modules/vite/dist/node/chunks/dep-CUvs3bbV.js:45978:627)
      at o (file:///Users/oskar/git/testproject/sb/node_modules/vite/dist/node/chunks/dep-CUvs3bbV.js:45978:1297)
      ...
 ```

**Comment by OskarPersson** [comment]
@alexgorbatchev Were you able to reproduce this?

**Comment by courtneycb** [comment]
I am also seeing this issue
>=> Failed to build the preview
Error: [commonjs--resolver] Missing "./dist/preview.js" specifier in "@alexgorbatchev/storybook-addon-localstorage" package

**Comment by alexgorbatchev** [comment]
I was able to reproduce the problem, but truth be told I'm not sure what the cause is. There IS `./dist/preview.js` file in module folder. It's unclear where this is coming from because there are no references to `preview` in the `dist` folder of the module. There has been a number of vite related issues (https://github.com/storybookjs/storybook/issues/23338 https://github.com/storybookjs/storybook/issues/20348) all of which are currently marked as resolved.

Finally, it's unclear where `./dist/preview.js` is being required from, creating this file in project root or in the `nnode_modules/vite/dist/node/chunks/dist` didn't fix the problem.

I would appreciate a PR or at least some pointers in the direction of the root cause.

**Comment by alexgorbatchev** [comment]
This was fixed in v10.0.0 — `./preview` is now properly included in the package exports.
